my_django/django_level_four/learning_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
]

my_django/django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')), #ini akan mencari urls ke alamat yang ada di basic app
]

my_django/django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

my_django/django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  context_dict = {'text':'hello world', 'number':100}
  return render(request, 'basic_app/index.html', context=context_dict)

def profile(request):
  return render(request, 'basic_app/profile.html')

def contact(request):
  return render(request, 'basic_app/contact.html')

my_django/django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to my site</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li>
            <a class="nav-link" href="{% url 'basic_app:profile' %}">Profile</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'basic_app:contact' %}">Contact</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!--content-->
      {% endblock %}
    </div>
  </body>
</html>

my_django/django_level_four/learning_templates/templates/basic_app/contact.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %} {% block body_block %}
<h1>This is contact.html</h1>
<p>This is the example of the template inheritance</p>
{% endblock %}

my_django/django_level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %} {% block body_block %}
<h1>This is index.html</h1>
<p>{{ text | cut:"hello" }}</p>
<p>{{ number | add:"99" }}</p>
{% endblock %}

my_django/django_level_four/learning_templates/templates/basic_app/profile.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %} {% block body_block %}
<h1>This is profile.html</h1>
<p>This is the example of the template inheritance</p>
{% endblock %}